name: Bankcraft
main: de.hotmail.gurkilein.Bankcraft.Bankcraft
version: 1.2
depend: [Vault]
commands:
   bank:
      description: Main Bankcraft Command
      usage: /bank
   bankadmin:
      description: Admin Bankcraft Command
      usage: /bankadmin
   bcreload:
      description: This Command reloads the Bankcraftconfig
      usage: Use this from the console only!
   bctimer:
      description: This Command restarts the Interesttimer
      usage: Use this from the console only"
permissions:
   bankcraft.use:
      description: Allows the use of the Bankcraftbanks
      default: true
   bankcraft.admin:
      description: Allows creating and removing Bankcraftbanks
      default: op
      